import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.gray200,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          disabledBackgroundColor: colorScheme.primary,
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(15.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.black90001.withOpacity(0.58),
          fontSize: 16.fSize,
          fontFamily: 'DM Serif Display',
          fontWeight: FontWeight.w400,
        ),
        displayMedium: TextStyle(
          color: appTheme.green90002,
          fontSize: 42.fSize,
          fontFamily: 'DM Serif Display',
          fontWeight: FontWeight.w400,
        ),
        displaySmall: TextStyle(
          color: appTheme.lightGreen900,
          fontSize: 35.fSize,
          fontFamily: 'DM Serif Display',
          fontWeight: FontWeight.w400,
        ),
        headlineLarge: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 30.fSize,
          fontFamily: 'DM Serif Display',
          fontWeight: FontWeight.w400,
        ),
        headlineMedium: TextStyle(
          color: appTheme.gray900,
          fontSize: 28.fSize,
          fontFamily: 'DM Serif Display',
          fontWeight: FontWeight.w400,
        ),
        headlineSmall: TextStyle(
          color: appTheme.gray900,
          fontSize: 25.fSize,
          fontFamily: 'DM Serif Display',
          fontWeight: FontWeight.w400,
        ),
        titleLarge: TextStyle(
          color: appTheme.lightGreen900,
          fontSize: 22.fSize,
          fontFamily: 'DM Serif Display',
          fontWeight: FontWeight.w400,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0X35D9D9D9),
    primaryContainer: Color(0XFF1E4628),
    secondary: Color(0XFF1E4628),
    secondaryContainer: Color(0XFFD6D6D6),
    tertiary: Color(0XFF1E4628),
    tertiaryContainer: Color(0XFFD6D6D6),

    // Background colors
    background: Color(0XFF1E4628),

    // Surface colors
    surface: Color(0XFF1E4628),
    surfaceTint: Color(0XFF043318),
    surfaceVariant: Color(0XFFD6D6D6),

    // Error colors
    error: Color(0XFF043318),
    errorContainer: Color(0XFF86AB89),
    onError: Color(0X35D9D9D9),
    onErrorContainer: Color(0XFF043318),

    // On colors(text colors)
    onBackground: Color(0X87FFFFFF),
    onInverseSurface: Color(0X35D9D9D9),
    onPrimary: Color(0XFF043318),
    onPrimaryContainer: Color(0X87FFFFFF),
    onSecondary: Color(0X87FFFFFF),
    onSecondaryContainer: Color(0XFF043318),
    onTertiary: Color(0X87FFFFFF),
    onTertiaryContainer: Color(0XFF043318),

    // Other colors
    outline: Color(0XFF043318),
    outlineVariant: Color(0XFF1E4628),
    scrim: Color(0XFF1E4628),
    shadow: Color(0XFF043318),

    // Inverse colors
    inversePrimary: Color(0XFF1E4628),
    inverseSurface: Color(0XFF043318),

    // Pending colors
    onSurface: Color(0X87FFFFFF),
    onSurfaceVariant: Color(0XFF043318),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000100);
  Color get black90001 => Color(0XFF000000);

  // BlueGray
  Color get blueGray400 => Color(0XFF888888);
  Color get blueGray700 => Color(0XFF4B5568);
  Color get blueGray70001 => Color(0XFF426D52);
  Color get blueGray900 => Color(0XFF263E30);

  // Gray
  Color get gray200 => Color(0XFFEDEDEF);
  Color get gray300 => Color(0XFFE3E3E3);
  Color get gray900 => Color(0XFF053418);

  // Green
  Color get green400 => Color(0XFF5EDB7D);
  Color get green50 => Color(0XFFE7EFE7);
  Color get green5001 => Color(0XFFE5EEE5);
  Color get green5002 => Color(0XFFE0EFE2);
  Color get green900 => Color(0XFF1B5820);
  Color get green90001 => Color(0XFF0E3E12);
  Color get green90002 => Color(0XFF1A571F);

  // LightGreen
  Color get lightGreen900 => Color(0XFF3D6803);

  // Lime
  Color get lime200 => Color(0XFFE3FFA8);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
